import { useState, useRef, useEffect } from 'react';
import { generateLocalBotResponse } from '../utils/botLogic';
import { Send, Bot, MoreHorizontal, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const NerveAI = () => {
    const [chatHistory, setChatHistory] = useState([]);
    const [inputValue, setInputValue] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const messagesEndRef = useRef(null);

    useEffect(() => {
        // Initialize chat on load
        initChat();
    }, []);

    useEffect(() => {
        scrollToBottom();
    }, [chatHistory, isLoading]);

    const initChat = () => {
        const initialMessage = "Hello! I am Nerve AI. I will ask you a few questions to understand your condition and prepare a comprehensive pre-treatment report for the doctor. Please describe your main symptoms.";
        setChatHistory([{ role: 'bot', text: initialMessage, isUser: false }]);
    };

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    const generatePDF = (historyToExport) => {
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Primary color
        doc.text("QuickOPD Triage Summary", 105, 20, { align: "center" });
        
        doc.setFontSize(14);
        doc.setTextColor(100, 100, 100);
        doc.text("Nerve AI Pre-Treatment Report", 105, 30, { align: "center" });
        
        doc.line(20, 35, 190, 35);
        
        // Prepare table data
        const tableData = [];
        let botMsg = "";
        
        historyToExport.forEach(msg => {
            // Clean HTML tags from bot text
            const textContent = msg.text.replace(/<[^>]*>?/gm, '');
            if (msg.role === 'bot') {
                botMsg = textContent;
            } else if (msg.role === 'user') {
                tableData.push([botMsg, textContent]);
                botMsg = ""; // reset for next pair
            }
        });
        
        doc.autoTable({
            startY: 45,
            head: [['Question / Prompt', 'Patient Response']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229] },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 90 },
                1: { cellWidth: 90 }
            }
        });
        
        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text(`Generated by QuickOPD Nerve AI - Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
        }
        
        doc.save("Triage_Summary_NerveAI.pdf");
    };

    const handleSend = async (textToUse) => {
        const text = typeof textToUse === 'string' ? textToUse : inputValue.trim();
        if (!text) return;

        const newHistory = [...chatHistory, { role: 'user', text: text, isUser: true }];
        setChatHistory(newHistory);
        setInputValue('');
        setIsLoading(true);

        try {
            // Using the same botLogic utility
            const data = await generateLocalBotResponse(newHistory);
            
            const botMessage = {
                role: 'bot',
                text: data.message,
                isUser: false,
                quickReplies: data.quick_replies
            };

            setChatHistory(prev => [...prev, botMessage]);

            if (data.conclusion_reached) {
                setTimeout(() => {
                    setChatHistory(prev => [
                        ...prev,
                        {
                            role: 'bot',
                            text: `<strong>Triage Complete.</strong> A summary has been generated. Please proceed to the clinic.`,
                            isUser: false,
                            isConclusion: true
                        }
                    ]);
                }, 1500);
            }
        } catch (error) {
            console.error('Chatbot error:', error);
            setChatHistory(prev => [
                ...prev,
                { role: 'bot', text: `<strong>System Error:</strong> ${error.message}`, isUser: false }
            ]);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="container animate-fade-in" style={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 100px)' }}>
            <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
                <h1>Nerve AI Questionnaire</h1>
                <p className="text-muted">Interactive Pre-Triage Assistant</p>
            </div>

            <div className="card" style={{ flexGrow: 1, display: 'flex', flexDirection: 'column', padding: '0', overflow: 'hidden' }}>
                <div style={{ background: 'var(--primary)', color: 'white', padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 'bold' }}>
                    <Bot size={24} /> Nerve AI Active
                </div>

                <div style={{ flexGrow: 1, overflowY: 'auto', padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem', background: 'var(--background)' }}>
                    {chatHistory.map((msg, idx) => (
                        <div key={idx} style={{ 
                            maxWidth: '80%', 
                            alignSelf: msg.isUser ? 'flex-end' : 'flex-start',
                            background: msg.isUser ? 'var(--primary)' : 'var(--surface)',
                            color: msg.isUser ? 'white' : 'var(--text-main)',
                            padding: '1rem 1.25rem',
                            borderRadius: '1rem',
                            borderBottomRightRadius: msg.isUser ? '0' : '1rem',
                            borderBottomLeftRadius: msg.isUser ? '1rem' : '0',
                            border: msg.isUser ? 'none' : '1px solid var(--border)',
                            boxShadow: 'var(--shadow-sm)'
                        }}>
                            <div dangerouslySetInnerHTML={{ __html: msg.text }} style={{ lineHeight: '1.5' }} />
                            
                            {msg.isConclusion && (
                                <button 
                                    onClick={() => generatePDF(chatHistory)}
                                    className="btn btn-primary"
                                    style={{ marginTop: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', borderRadius: '2rem', padding: '0.5rem 1rem' }}
                                >
                                    <Download size={18} /> Download Summary PDF
                                </button>
                            )}
                            
                            {msg.quickReplies && msg.quickReplies.length > 0 && (
                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                                    {msg.quickReplies.map((reply, rIdx) => (
                                        <button 
                                            key={rIdx} 
                                            onClick={() => handleSend(reply)}
                                            style={{
                                                background: 'rgba(79, 70, 229, 0.1)',
                                                color: 'var(--primary)',
                                                border: '1px solid rgba(79, 70, 229, 0.2)',
                                                padding: '0.5rem 1rem',
                                                borderRadius: '2rem',
                                                cursor: 'pointer',
                                                fontSize: '0.9rem',
                                                transition: 'var(--transition)'
                                            }}
                                            onMouseOver={(e) => { e.currentTarget.style.background = 'var(--primary)'; e.currentTarget.style.color = 'white'; }}
                                            onMouseOut={(e) => { e.currentTarget.style.background = 'rgba(79, 70, 229, 0.1)'; e.currentTarget.style.color = 'var(--primary)'; }}
                                        >
                                            {reply}
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>
                    ))}
                    {isLoading && (
                        <div style={{ 
                            alignSelf: 'flex-start', 
                            background: 'var(--surface)', 
                            padding: '1rem 1.25rem', 
                            borderRadius: '1rem', 
                            borderBottomLeftRadius: '0', 
                            border: '1px solid var(--border)' 
                        }}>
                            <MoreHorizontal className="animate-pulse" color="var(--primary)" />
                        </div>
                    )}
                    <div ref={messagesEndRef} />
                </div>

                <div style={{ padding: '1rem', background: 'var(--surface)', borderTop: '1px solid var(--border)', display: 'flex', gap: '1rem' }}>
                    <input 
                        type="text" 
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                        placeholder="Type your response here..." 
                        style={{ flexGrow: 1, padding: '0.75rem 1.5rem', borderRadius: '2rem', border: '1px solid var(--border)', background: 'var(--background)', outline: 'none' }}
                    />
                    <button 
                        onClick={handleSend}
                        style={{ width: '48px', height: '48px', borderRadius: '50%', background: 'var(--primary)', color: 'white', border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}
                    >
                        <Send size={20} style={{ marginLeft: '-2px' }} />
                    </button>
                </div>
            </div>
        </div>
    );
};

export default NerveAI;
